### ISSUE TITLE
it's seems this package don't support v2 protocol , right ? 

### ISSUE THREAD

**Issue by yanweimin7** [mofalabs/sui#7]
when i use 
```dart
TransactionBlock.from(data);
```

to decode data 
```
{
  "version": 2,
  "sender": null,
  "expiration": null,
  "gasData": {
    "budget": null,
    "price": null,
    "owner": null,
    "payment": null
  },
  "inputs": [
    {
      "UnresolvedObject": {
        "objectId": "0x0000000000000000000000000000000000000000000000000000000000000006"
      }
    },
    {
      "UnresolvedObject": {
        "objectId": "0xbb4e2f4b6205c2e2a2db47aeb4f830796ec7c005f88537ee775986639bc442fe"
      }
    },
    {
      "UnresolvedObject": {
        "objectId": "0x96df0fce3c471489f4debaaa762cf960b3d97820bd1f3f025ff8190730e958c5"
      }
    },
    {
      "Pure": {
        "bytes": "AA=="
      }
    },
    {
      "Pure": {
        "bytes": "APIFKgEAAAA="
      }
    },
    {
      "Pure": {
        "bytes": "APIFKgEAAAA="
      }
    },
    {
      "UnresolvedObject": {
        "objectId": "0xaaf735bf83ff564e1b219a0d644de894ef5bdc4b2250b126b2a46dd002331821"
      }
    },
    {
      "UnresolvedObject": {
        "objectId": "0xf87a8acb8b81d14307894d12595541a73f19933f88e1326d5be349c7a6f7559c"
      }
    }
  ],
  "commands": [
    {
      "SplitCoins": {
        "coin": {
          "GasCoin": true
        },
        "amounts": [
          {
            "Input": 4
          }
        ]
      }
    },
    {
      "MoveCall": {
        "package": "0xc6374c7da60746002bfee93014aeb607e023b2d6b25c9e55a152b826dbc8c1ce",
        "module": "incentive_v2",
        "function": "entry_deposit",
        "typeArguments": [
          "0x2::sui::SUI"
        ],
        "arguments": [
          {
            "Input": 0
          },
          {
            "Input": 1
          },
          {
            "Input": 2
          },
          {
            "Input": 3
          },
          {
            "Result": 0
          },
          {
            "Input": 5
          },
          {
            "Input": 6
          },
          {
            "Input": 7
          }
        ]
      }
    }
  ]
}
```

it throw 
```
I/flutter ( 5422): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5422): type 'Null' is not a subtype of type 'Map<String, dynamic>'
I/flutter ( 5422): #0      new SerializedTransactionDataBuilder.fromJson (package:sui/builder/transaction_block_data.dart:87:41)
I/flutter ( 5422): #1      TransactionBlockDataBuilder.restore (package:sui/builder/transaction_block_data.dart:160:40)
I/flutter ( 5422): #2      TransactionBlock.from (package:sui/builder/transaction_block.dart:158:47)
I/flutter ( 5422): #3      SuiWallet.buildTransactionBlock (package:bepro/src/biz/web3/lib/wallet_core/mnemonic/sui_wallet.dart:21:36)
I/flutter ( 5422): #4      _State.setupGas (package:bepro/src/biz/web3/lib/components/dialog/sui_transaction_confirm_dialog.dart:108:36)
I/flutter ( 5422): #5      _State.initState (package:bepro/src/biz/web3/lib/components/dialog/sui_transaction_confirm_dialog.dart:77:5)
I/flutter ( 5422): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5611:55)
I/flutter ( 5422): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
I/flutter ( 5422): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
I/flutter ( 5422): #9      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
I/flutter ( 5422): #10     MultiChild
```

**Comment by 0xmove** [comment]
Yes, it's still in progress, you can also submit a PR.

**Comment by 0xmove** [comment]
Could you try version 0.3.0 again?
